spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    user: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/exchange
    locations: filesystem:db/migration
    baselineOnMigrate: true